### ISSUE TITLE
Cannot install with bundler a gem

### ISSUE THREAD

**Issue by epinault** [bundler/bundler-features#94]
So I am trying instal the  tf-idf-similarity 0.1.4 gem.  that install works fine with  gem install  tf-idf-similarity

I have : 
```
bundle env
Environment

    Bundler   1.10.6
    Rubygems  2.4.8
    Ruby      2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
    Git       1.9.1

Bundler settings

    jobs
      Set for your local app (/mnt/webdeploy/feeder/.bundle/config): "3"
    without
      Set for your local app (/mnt/webdeploy/feeder/.bundle/config): "development,test:development:test"

```
But trying to use bundle install I get the following. Unfortunately none of the log exists when looking for them nor do I understand why it is failing at this point.

```
Installing tf-idf-similarity 0.1.4 with native extensions
Building native extensions.  This could take a while...

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby mkrf_conf.rb

rake failed, exit code 1

Gem files will remain installed in /tmp/bundler20151019-25135-1xbo1m8tf-idf-similarity-0.1.4/gems/tf-idf-similarity-0.1.4 for inspection.
Results logged to /tmp/bundler20151019-25135-1xbo1m8tf-idf-similarity-0.1.4/extensions/x86_64-linux/2.1.0-static/tf-idf-similarity-0.1.4/gem_make.out
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/rake_builder.rb:13:in `build'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:160:in `chdir'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:160:in `block in build_extension'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:159:in `build_extension'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:195:in `each'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:195:in `build_extensions'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:702:in `build_extensions'
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/installer.rb:250:in `install'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:141:in `block in install'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/rubygems_integration.rb:147:in `preserve_paths'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/source/rubygems.rb:134:in `install'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/installer.rb:112:in `install_gem_from_spec'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/installer/parallel_installer.rb:81:in `block in worker_pool'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:55:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:55:in `apply_func'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:50:in `block in process_queue'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:47:in `loop'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:47:in `process_queue'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler/worker.rb:22:in `block (2 levels) in initialize'
An error occurred while installing tf-idf-similarity (0.1.4), and Bundler cannot continue.
Make sure that `gem install tf-idf-similarity -v '0.1.4'` succeeds before bundling.
```

**Comment by segiddins** [comment]
Did you follow the instruction in the last line of the error?
`Make sure that `gem install tf-idf-similarity -v '0.1.4'` succeeds before bundling.`

Additionally, this repository is for requesting new features for bundler, and not for reporting bugs.

**Comment by epinault** [comment]
Yes, I tried and it works fine when I do gem install  . Hence why I don t know why it does not work with bundler . Still get that same error despite installing it manually

**Comment by indirect** [comment]
Please open a new issue on bundler/bundler for this, and please show us the contents of the make log (the path is printed in the error message).

**Comment by epinault** [comment]
@indirect I would love to, but the file is nowhere to be found! Despite that parth printed in the error message). It is never created , nor any folder in that path. Hence why I cannot even debug it. I even ran it with --verbose to help see details but not working either
